spring:
#  datasource: #띄어쓰기 2칸
#    url: jdbc:h2:tcp://localhost/~/myshopping #4칸
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/myshopping?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: myuser
    password: myuser123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false #false 하면 LazyinitializationException 많이 터짐.
    hibernate:
      ddl-auto: create #띄어쓰기 6칸
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        show_sql: true #띄어쓰기 8칸
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace # ? 에 바인딩 되는 파라미터 값 상세 출력.


springdoc:
  api-docs:
    enabled: true #자동 생성 비활성화
  swagger-ui:
    urls:
      - name: 자동 생성 API
        url: /v3/api-docs
      - name: 수동 작성 문서
        url: /openapi.yaml
