spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myshopping?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: myuser
    password: myuser123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
#    baseline-on-migrate: true #DB가 비어있지 않아도 마이그레이션을 시작하게 함
#    baseline-version: 1 #현재 DB 상태를 버전 1로 간주함.
#    repair: true

logging.level:
  myex.shopping: INFO
  org.hibernate.SQL: info
  org.hibernate.orm.jdbc.bind: trace

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: 자동 생성 API
        url: /v3/api-docs
